image: node:11.3.0

pipelines:
  branches:
    master:
      - step:
          name: Deploy
          deployment: production
          script:
            - npm ci
            - npm run build
            - docker login bc1.lition.io:5000 -u $DOCKER_USER -p $DOCKER_PASSWORD
            - docker build -t smart-contract-viewer .
            - docker tag smart-contract-viewer bc1.lition.io:5000/smart-contract-viewer
            - docker push bc1.lition.io:5000/smart-contract-viewer
            - ssh lition@bc1.lition.io "docker pull bc1.lition.io:5000/smart-contract-viewer"
            - ssh lition@bc1.lition.io "docker stop smart-contract-viewer || true"
            - ssh lition@bc1.lition.io "docker rm smart-contract-viewer || true"
            - ssh lition@bc1.lition.io "docker run --network nginx --network-alias smart-contract-viewer --name smart-contract-viewer -d bc1.lition.io:5000/smart-contract-viewer"

options:
  docker: true
